version: '3'
services:
  postgres:
    build: ./db
    container_name: "app_db"
    volumes:
      - /db/data:/volume
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=app_db
      - PGDATA=/volume/data
      - NETWORK_ACCESS=internal

  datos:
    build: ./src/datos
    restart: always
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - postgres
    links:
      - postgres

  nginx:
    image: nginx:1.15
    restart: always
    container_name: "nginx-app"
    expose:
      - "80"
    volumes:
      - ./balancer:/etc/nginx/conf.d:ro
    environment:
      - VIRTUAL_HOST=lala.sytes.net,www.lala.sytes.net
      - LETSENCRYPT_HOST=lala.sytes.net,www.lala.sytes.net
      - LETSENCRYPT_EMAIL=mmbarja@gmail.com
    depends_on:
      - nginx-proxy
      - letsencrypt
      - datos

  nginx-proxy:
    image: jwilder/nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - certs:/etc/nginx/certs:ro
      - vhostd:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
    volumes:
      - certs:/etc/nginx/certs:rw
      - vhostd:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - nginx-proxy

volumes:
  certs:
  html:
  vhostd: